# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackifyMarkdown < Formula
  desc "Convert Markdown to Slack formatting"
  homepage "https://github.com/robmathews/slackify-markdown"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Darwin_x86_64.tar.gz"
      sha256 "d7319225dbd4a0f2a64cd6e8a7b85f6dee4e142cbfd1cc60b7e9ff602a715257"

      def install
        bin.install "slackify-markdown"
      end
    end
    on_arm do
      url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Darwin_arm64.tar.gz"
      sha256 "ae7af52a38e71fd8f9f9db87d099862488a4d5b163daa2bd4efb56e5bd7f2f1c"

      def install
        bin.install "slackify-markdown"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Linux_x86_64.tar.gz"
        sha256 "e9c9516334a8ac082b1ae3a81d61f44820f6e7232d8b91256ccec3413b4b37d4"

        def install
          bin.install "slackify-markdown"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Linux_arm64.tar.gz"
        sha256 "647cf86e44321914f2e6433c4176d44f420314fcf74c9f0abd8d5947f83d4713"

        def install
          bin.install "slackify-markdown"
        end
      end
    end
  end

  test do
    system "#{bin}/slackify-markdown --help"
  end
end
