# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackifyMarkdown < Formula
  desc "Convert Markdown to Slack formatting"
  homepage "https://github.com/robmathews/slackify-markdown"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Darwin_x86_64.tar.gz"
      sha256 "3ebc62cd8303acb69fcd722f11565efc6faa4ad60309271dea3e79b18960686b"

      def install
        bin.install "slackify-markdown"
      end
    end
    on_arm do
      url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Darwin_arm64.tar.gz"
      sha256 "2f3abfcb07b6b66ab88b733814134d31b40ce37a813863e482156dee5bd8c79c"

      def install
        bin.install "slackify-markdown"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Linux_x86_64.tar.gz"
        sha256 "c8b4b749e1f0d55b2d4415ddd23e41fb46e2a258bacbed335c10df3453de070c"

        def install
          bin.install "slackify-markdown"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Linux_arm64.tar.gz"
        sha256 "e2c73d71d7aa97f6e4dbf744217af6dcca54a27a06f1f7207154fdd8dea0f368"

        def install
          bin.install "slackify-markdown"
        end
      end
    end
  end

  test do
    system "#{bin}/slackify-markdown --help"
  end
end
