# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackifyMarkdown < Formula
  desc "Convert Markdown to Slack formatting"
  homepage "https://github.com/robmathews/slackify-markdown"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Darwin_x86_64.tar.gz"
      sha256 "c4dad16377320e1d20b18cc71508294649c6765b2a4c5f5ea4ea24544af900e9"

      def install
        bin.install "slackify-markdown"
      end
    end
    on_arm do
      url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Darwin_arm64.tar.gz"
      sha256 "8fe7b5970d55504a7cd2c910618c8ea91a54ad8fa82e20c1ce328f9fb0af9bc0"

      def install
        bin.install "slackify-markdown"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Linux_x86_64.tar.gz"
        sha256 "660b9037756458eaebefde1529d6f683f4021a3c848f91c15e6d8d5e2ee96ba1"

        def install
          bin.install "slackify-markdown"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Linux_arm64.tar.gz"
        sha256 "15853bc8de09a0df5bf426d12a23772c5297f1cb6037e70a2ce033d851bb9409"

        def install
          bin.install "slackify-markdown"
        end
      end
    end
  end

  test do
    system "#{bin}/slackify-markdown --help"
  end
end
