# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlackifyMarkdown < Formula
  desc "Convert Markdown to Slack formatting"
  homepage "https://github.com/robmathews/slackify-markdown"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Darwin_x86_64.tar.gz"
      sha256 "949bd2f0d6344fceb8dd25e4b4c5b86370ccc2c9c0e01b0c55aa60f86f7a0d8e"

      def install
        bin.install "slackify-markdown"
      end
    end
    on_arm do
      url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Darwin_arm64.tar.gz"
      sha256 "b51d27dc97b517c8b3b814ba9d34fa51e70ddcebd6fe36548c2342a81ad6bbc7"

      def install
        bin.install "slackify-markdown"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Linux_x86_64.tar.gz"
        sha256 "cc100d7d6671645775841468f8b3bb0766a245a0d31d346341be699bf99115c1"

        def install
          bin.install "slackify-markdown"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/robmathews/slackify-markdown/releases/download/v1.0.0/slackify-markdown_Linux_arm64.tar.gz"
        sha256 "40848f7cd9dac0d8b61826c81fafe31c84c0db6c52ac83220fb92b86f8fd0e56"

        def install
          bin.install "slackify-markdown"
        end
      end
    end
  end

  test do
    system "#{bin}/slackify-markdown --help"
  end
end
